---
  Resources:
    LockitLogGroup:
      Type: AWS::IAM::Group
      Properties:
        GroupName: LockitLogGroup
        Path: /Lockit/
        Policies:
          - PolicyName: LockitLogWritePolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource: arn:aws:dynamodb:undefined:undefined:table/LockitLogging
    LockitLogging:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LockitLogging
        AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5